### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by fgregg** [datamade/million-dollar-blocks#21]
## Framing / Call to Action
- [x] Make sure that the site has a clear call to action. This should not be 'hey look at this cool tool'. Rather, it should be a way for someone to engage in a meaningful way on the issue being presented.

Some examples:
- Join a mailing list (which means you need to create one)
- Attend an event
- Share on Facebook/Twitter
- Donate to a particular organization
- Create a Tumblr for people to share interesting findings (if it's a data access site)
## Google Analytics
- [x] Create [Google Analytics](http://www.google.com/analytics/) account
- [x] Hook up the GA Tracking Code (typically in our `analytics_lib.js` file)
- [x] Set up relevant Goals and Funnels
- [x] Set up [Google Webmaster Tools](https://www.google.com/webmasters/tools/home?hl=en)
- [x] Verify site in Webmaster Tools with DNS TXT record
- [x] Link Webmaster Tools to Google Analytics
## Sharing & Rich Snippets
- [x] Set up Twitter, Facebook and general meta tags with
  - title
  - URL
  - description
  - image
- [x] Create 2-5 meme images using [Canva](http://canva.com/) or a similar tool
## Outreach
- [x] Write up press release
- [x] Identify who will be the primary person of contact and make their info prominent on the website and all PR
- [x] Identify relevant media contacts to email
- [x] Identify relevant social news sites (reddit, listservs, slack channels)
- [x] Divide & conquer - send out the media blitz!
